# Generated by Django 6.0.6 on 2026-09-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_designation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name of User'),
        ),
    ]
