# Generated by Django 6.0.6 on 2026-09-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin_supervisor', 'Admin / Supervisor'), ('commissioner', 'Commissioner IR (View Only)'), ('data_entry', 'Data Entry Operator')], default='data_entry', max_length=30, verbose_name='Role'),
        ),
    ]
