"""Turn the free-text designation into a managed lookup.

Written by hand rather than autogenerated so the designations already typed
against existing users are preserved: the text is read, turned into
Designation rows, and re-attached before the old column is dropped.
"""

import django.db.models.deletion
from django.db import migrations, models

#: Standard postings for the office, seeded so the list is usable immediately.
#: Anything already typed against a user is added on top of these.
STANDARD = [
    ("Commissioner Inland Revenue (Appeals)", "CIR (A)", 10),
    ("Additional Commissioner Inland Revenue", "Addl. CIR", 20),
    ("Deputy Commissioner Inland Revenue", "DCIR", 30),
    ("Assistant Commissioner Inland Revenue", "ACIR", 40),
    ("Inland Revenue Officer", "IRO", 50),
    ("Superintendent", "Supdt.", 60),
    ("Inspector Inland Revenue", "Inspector", 70),
    ("Appraising Officer", "AO", 80),
    ("Stenographer", "Steno", 90),
    ("Upper Division Clerk", "UDC", 100),
    ("Lower Division Clerk", "LDC", 110),
    ("Naib Qasid", "NQ", 120),
]


def forwards(apps, schema_editor):
    Designation = apps.get_model("accounts", "Designation")
    User = apps.get_model("accounts", "User")

    for name, short, order in STANDARD:
        Designation.objects.get_or_create(
            name=name, defaults={"short_name": short, "order": order}
        )

    # Preserve whatever was already typed, even if it is not in the standard
    # list - losing a real posting title would be worse than an untidy list.
    next_order = 200
    for user in User.objects.exclude(designation="").exclude(designation=None):
        title = (user.designation or "").strip()
        if not title:
            continue
        obj = Designation.objects.filter(name__iexact=title).first()
        if obj is None:
            obj = Designation.objects.create(name=title, order=next_order)
            next_order += 10
        user.designation_ref = obj
        user.save(update_fields=["designation_ref"])


def backwards(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.select_related("designation_ref"):
        if user.designation_ref_id:
            user.designation = user.designation_ref.name
            user.save(update_fields=["designation"])


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_alter_user_role")]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True,
                                          verbose_name="Designation")),
                ("short_name", models.CharField(blank=True, max_length=30,
                                                verbose_name="Short Form")),
                ("order", models.PositiveSmallIntegerField(default=0,
                                                           verbose_name="Display Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Designation",
                "verbose_name_plural": "Designations",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="designation_ref",
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users", to="accounts.designation",
                verbose_name="Designation",
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(model_name="user", name="designation"),
        migrations.RenameField(
            model_name="user", old_name="designation_ref", new_name="designation"
        ),
    ]
