# Generated by Django 6.0.6 on 2026-09-04 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Zone Name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Unit Name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='appeals.zone', verbose_name='Zone')),
            ],
            options={
                'ordering': ['zone__order', 'order', 'name'],
                'unique_together': {('zone', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SalesTaxAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_no', models.CharField(max_length=50, unique=True, verbose_name='Appeal No.')),
                ('date_of_institution', models.DateField(verbose_name='Date of Institution')),
                ('ntn', models.CharField(blank=True, db_index=True, max_length=15, verbose_name='NTN')),
                ('appellant_name', models.CharField(db_index=True, max_length=255, verbose_name='Name of Appellant')),
                ('contact_no', models.CharField(blank=True, max_length=30, verbose_name='Contact No.')),
                ('first_expiry_120', models.DateField(blank=True, editable=False, null=True, verbose_name='First Expiry (120 Days)')),
                ('second_expiry_180', models.DateField(blank=True, editable=False, null=True, verbose_name='2nd Expiry (180 Days)')),
                ('courier_no', models.CharField(blank=True, max_length=100, verbose_name='Courier No.')),
                ('courier_date', models.DateField(blank=True, null=True, verbose_name='Courier Date')),
                ('service_status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='pending', max_length=20, verbose_name='Service Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strn', models.CharField(blank=True, max_length=20, verbose_name='STRN')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('sales_tax_involved', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Sales Tax Involved')),
                ('passing_officer_name', models.CharField(blank=True, max_length=150, verbose_name='Passing Officer Name')),
                ('tax_period', models.CharField(blank=True, max_length=50, verbose_name='Tax Period')),
                ('oio_no', models.CharField(blank=True, max_length=100, verbose_name='Order-In-Original No.')),
                ('oio_date', models.DateField(blank=True, null=True, verbose_name='Order-In-Original Date')),
                ('ar_name', models.CharField(blank=True, max_length=150, verbose_name='Name of AR')),
                ('ar_contact_no', models.CharField(blank=True, max_length=30, verbose_name='Contact No. of AR')),
                ('issue_involved', models.TextField(blank=True, verbose_name='Issue Involved')),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='Section')),
                ('oia_no', models.CharField(blank=True, max_length=100, verbose_name='Order-In-Appeal No.')),
                ('oia_date', models.DateField(blank=True, null=True, verbose_name='Order-In-Appeal Date')),
                ('decision_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('annulled', 'Annulled'), ('modified', 'Modified'), ('remand_back', 'Remand Back'), ('others', 'Others')], default='pending', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='appeals.unit', verbose_name='Unit')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='appeals.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Sales Tax Appeal',
                'verbose_name_plural': 'Sales Tax Appeals',
                'ordering': ['-date_of_institution', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeTaxAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_no', models.CharField(max_length=50, unique=True, verbose_name='Appeal No.')),
                ('date_of_institution', models.DateField(verbose_name='Date of Institution')),
                ('ntn', models.CharField(blank=True, db_index=True, max_length=15, verbose_name='NTN')),
                ('appellant_name', models.CharField(db_index=True, max_length=255, verbose_name='Name of Appellant')),
                ('contact_no', models.CharField(blank=True, max_length=30, verbose_name='Contact No.')),
                ('first_expiry_120', models.DateField(blank=True, editable=False, null=True, verbose_name='First Expiry (120 Days)')),
                ('second_expiry_180', models.DateField(blank=True, editable=False, null=True, verbose_name='2nd Expiry (180 Days)')),
                ('courier_no', models.CharField(blank=True, max_length=100, verbose_name='Courier No.')),
                ('courier_date', models.DateField(blank=True, null=True, verbose_name='Courier Date')),
                ('service_status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='pending', max_length=20, verbose_name='Service Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cnic', models.CharField(blank=True, max_length=15, verbose_name='CNIC')),
                ('address_line_1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('tax_year', models.CharField(blank=True, max_length=10, verbose_name='Tax Year')),
                ('order_section', models.CharField(blank=True, max_length=50, verbose_name='Order Section')),
                ('income_assessed', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Income Assessed')),
                ('revenue_involved', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Revenue Involved')),
                ('date_of_assessment', models.DateField(blank=True, null=True, verbose_name='Date of Assessment')),
                ('officer_name', models.CharField(blank=True, max_length=150, verbose_name='Name of Officer')),
                ('issues_involved', models.TextField(blank=True, verbose_name='Issues Involved')),
                ('ar_name', models.CharField(blank=True, max_length=150, verbose_name='Advocate / ITP / AR')),
                ('appellate_order_date', models.DateField(blank=True, null=True, verbose_name='Date of Appellate Order')),
                ('decision_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('annulled', 'Annulled'), ('modified', 'Modified'), ('remand_back', 'Remand Back')], default='pending', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='appeals.unit', verbose_name='Unit')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='appeals.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Income Tax Appeal',
                'verbose_name_plural': 'Income Tax Appeals',
                'ordering': ['-date_of_institution', '-id'],
                'abstract': False,
            },
        ),
    ]
