# Generated by Django 6.0.6 on 2026-09-04 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incometaxappeal',
            options={'ordering': ['-year', '-serial_no'], 'verbose_name': 'Income Tax Appeal', 'verbose_name_plural': 'Income Tax Appeals'},
        ),
        migrations.AlterModelOptions(
            name='salestaxappeal',
            options={'ordering': ['-year', '-serial_no'], 'verbose_name': 'Sales Tax Appeal', 'verbose_name_plural': 'Sales Tax Appeals'},
        ),
        migrations.RemoveField(
            model_name='incometaxappeal',
            name='appeal_no',
        ),
        migrations.RemoveField(
            model_name='salestaxappeal',
            name='appeal_no',
        ),
        migrations.AddField(
            model_name='incometaxappeal',
            name='serial_no',
            field=models.PositiveIntegerField(default=1, verbose_name='Appeal No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incometaxappeal',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2026, editable=False, verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestaxappeal',
            name='serial_no',
            field=models.PositiveIntegerField(default=1, verbose_name='Appeal No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestaxappeal',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2026, editable=False, verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='incometaxappeal',
            constraint=models.UniqueConstraint(fields=('serial_no', 'year'), name='unique_income_tax_appeal_no'),
        ),
        migrations.AddConstraint(
            model_name='salestaxappeal',
            constraint=models.UniqueConstraint(fields=('serial_no', 'year'), name='unique_sales_tax_appeal_no'),
        ),
    ]
