# Generated by Django 6.0.6 on 2026-09-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_alter_incometaxappeal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxappeal',
            name='created_by_name',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='Registered By'),
        ),
        migrations.AddField(
            model_name='incometaxappeal',
            name='updated_by_name',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='salestaxappeal',
            name='created_by_name',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='Registered By'),
        ),
        migrations.AddField(
            model_name='salestaxappeal',
            name='updated_by_name',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='Last Updated By'),
        ),
    ]
