# Generated by Django 6.0.6 on 2026-09-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_incometaxappeal_created_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxappeal',
            name='ar_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address of AR'),
        ),
        migrations.AddField(
            model_name='incometaxappeal',
            name='ar_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City of AR'),
        ),
        migrations.AddField(
            model_name='incometaxappeal',
            name='ar_contact_no',
            field=models.CharField(blank=True, max_length=60, verbose_name='Contact No. of AR'),
        ),
        migrations.AddField(
            model_name='incometaxappeal',
            name='ar_registration_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Registration No. of AR'),
        ),
        migrations.AddField(
            model_name='incometaxappeal',
            name='ar_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='AR Type'),
        ),
        migrations.AddField(
            model_name='incometaxappeal',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='incometaxappeal',
            name='date_of_service',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Service of Order'),
        ),
        migrations.AddField(
            model_name='salestaxappeal',
            name='ar_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address of AR'),
        ),
        migrations.AddField(
            model_name='salestaxappeal',
            name='ar_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City of AR'),
        ),
        migrations.AddField(
            model_name='salestaxappeal',
            name='ar_registration_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Registration No. of AR'),
        ),
        migrations.AddField(
            model_name='salestaxappeal',
            name='ar_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='AR Type'),
        ),
        migrations.AddField(
            model_name='salestaxappeal',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='salestaxappeal',
            name='date_of_service',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Service of Order'),
        ),
        migrations.AddField(
            model_name='salestaxappeal',
            name='tax_year',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tax Year'),
        ),
        migrations.AlterField(
            model_name='incometaxappeal',
            name='ar_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name of AR'),
        ),
        migrations.AlterField(
            model_name='salestaxappeal',
            name='ar_contact_no',
            field=models.CharField(blank=True, max_length=60, verbose_name='Contact No. of AR'),
        ),
    ]
