# Generated by Django 6.0.6 on 2026-09-08 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0004_incometaxappeal_ar_address_incometaxappeal_ar_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='incometaxappeal',
            name='unique_income_tax_appeal_no',
        ),
        migrations.RemoveConstraint(
            model_name='salestaxappeal',
            name='unique_sales_tax_appeal_no',
        ),
        migrations.AddField(
            model_name='incometaxappeal',
            name='serial_suffix',
            field=models.CharField(blank=True, max_length=5, verbose_name='Suffix'),
        ),
        migrations.AddField(
            model_name='salestaxappeal',
            name='serial_suffix',
            field=models.CharField(blank=True, max_length=5, verbose_name='Suffix'),
        ),
        migrations.AddConstraint(
            model_name='incometaxappeal',
            constraint=models.UniqueConstraint(fields=('serial_no', 'serial_suffix', 'year'), name='unique_income_tax_appeal_no'),
        ),
        migrations.AddConstraint(
            model_name='salestaxappeal',
            constraint=models.UniqueConstraint(fields=('serial_no', 'serial_suffix', 'year'), name='unique_sales_tax_appeal_no'),
        ),
    ]
