# Generated by Django 6.0.6 on 2026-09-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0005_remove_incometaxappeal_unique_income_tax_appeal_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxappeal',
            name='officer_designation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Designation of Officer'),
        ),
    ]
